/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/renderer/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class', // 启用 class 策略的深色模式
  theme: {
    extend: {
      colors: {
        // 自定义颜色变量
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        text: 'var(--color-text)',
        textSecondary: 'var(--color-textSecondary)',
        border: 'var(--color-border)',
        accent: 'var(--color-accent)',
        error: 'var(--color-error)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
      },
      fontFamily: {
        body: 'var(--font-body)',
        heading: 'var(--font-heading)',
        mono: 'var(--font-mono)',
      },
    },
  },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
  daisyui: {
    themes: [
      {
        light: {
          primary: '#3B82F6',
          secondary: '#6B7280',
          accent: '#10B981',
          neutral: '#374151',
          'base-100': '#FFFFFF',
          'base-200': '#F9FAFB',
          'base-300': '#F3F4F6',
          info: '#3B82F6',
          success: '#10B981',
          warning: '#F59E0B',
          error: '#EF4444',
        },
        dark: {
          primary: '#60A5FA',
          secondary: '#9CA3AF',
          accent: '#34D399',
          neutral: '#6B7280',
          'base-100': '#1F2937',
          'base-200': '#111827',
          'base-300': '#374151',
          info: '#60A5FA',
          success: '#34D399',
          warning: '#FBBF24',
          error: '#F87171',
        },
        sepia: {
          primary: '#8B4513',
          secondary: '#A0522D',
          accent: '#795548',
          neutral: '#5D4037',
          'base-100': '#F5F1EB',
          'base-200': '#FDF8F3',
          'base-300': '#D7CCC8',
          info: '#8B4513',
          success: '#388E3C',
          warning: '#F57C00',
          error: '#D32F2F',
        },
      },
    ],
    darkTheme: 'dark',
    base: true,
    styled: true,
    utils: true,
    prefix: '',
    logs: true,
    themeRoot: ':root',
  },
};
